image: python:3.6-alpine

stages:
  - test
  - pack
  - deploy

black:
  stage: test
  image: kiwicom/black:19.10b0
  script:
    - black --check .
  allow_failure: true

package:
  stage: pack
  script:
    - apk update
    - apk add git
    - python setup.py sdist bdist_wheel
  artifacts:
    when: on_success
    paths:
      - dist/
    expire_in: 1 week

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v_/'
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - apk update
    - apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo
    - pip install twine
    - echo twine upload dist/*

