image: python:3.6-alpine

stages:
  - test
  - deploy

black:
  stage: test
  image: kiwicom/black:19.10b0
  script:
    - black --check .
  allow_failure: true

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - apk update
    - apk add gcc musl-dev libffi-dev libressl-dev
    - pip install cryptography==3.3.1
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - master
