image: python:3.6-alpine

stages:
  - test
  - deploy

black:
  stage: test
  image: python:alpine
  script:
    - apk update
    - apk add gcc musl-dev
    - pip install black
    - black --check --line-length 120 .
  allow_failure: true

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - apk update
    - apk add gcc musl-dev libffi-dev
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
