repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools, types-requests]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        language_version: python3
        additional_dependencies: [requests==2.21.0, opencv-contrib-python-headless>=4.1.2.30, pytest>=3.0.3, pytest-mock, tqdm==4.31.1]
        always_run: true
        pass_filenames: false
  - repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        additional_dependencies: [requests==2.21.0, opencv-contrib-python-headless>=4.1.2.30, pytest>=3.0.3, pytest-mock, tqdm==4.31.1]
        args: ["ximilar/client2", "tests/client2"]
        always_run: true
        pass_filenames: false
